// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/docs': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs.post').default>>>>
    }
    '/api/export': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/export').default>>>>
    }
    '/api/repos': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/repos').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/registry.npmmirror.com+nuxt@3.3.3_ntigm5zxnpdibkyr63irmrr6ve/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}